### ISSUE TITLE
Different Values at Different Breakpoints

### ISSUE THREAD

**Issue by picosam** [buildo/react-flexview#59]
Hello, how do I set values differently at different breakpoints? Say for instance that I want a sidebar to collapse entirely but only on mobile screens?

**Comment by FrancescoCioria** [comment]
Hi @picosam 

You can detect the device's screen size from JavaScript using ['window.matchMedia`](https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia) and then generate a different set of `props` for `FlexView` for each breakpoint.

There are also some open source react components that may help you with that like:
- https://github.com/bloodyowl/react-media-queries
- https://github.com/contra/react-responsive

In one of our project we built a wrapper named `ResponsiveFlexView` that could receive an object for each breakpoint as prop and then automatically use the correct one based on which media query matched (we used `window.matchMedia`).

PS: if you prefer to detect the type of device instead of the screen size, I suggest you use [`mobile-detect`](https://github.com/hgoebl/mobile-detect.js): I personally prefer this solution of media queries responsiveness.

**Comment by picosam** [comment]
Thank you! In that case I'd prefer using something like https://github.com/emotion-js/facepaint to construct an array of media queries.
